name: bellboy_ride
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
  - family: Lato
    fonts:
      - asset: assets/fonts/Lato/Lato-Regular.ttf
      - asset: assets/fonts/Lato/Lato-Bold.ttf
      - asset: assets/fonts/Lato/Lato-Italic.ttf

get_cli: 
  separator: .

